### ISSUE TITLE
Applying specifity and selectivity

### ISSUE THREAD

**Issue by MetaColon** [MetaColon/PfN-Project#13]
The known constants of specifity and selectivity should be applied to the data in a meaningful way.

**Comment by MetaColon** [comment]
Please note that the topics specifity and selectivity can also be handled separately, hence it's ok if two peoply are assigned here.

**Comment by RalfSchmelcher** [comment]
I think that the best way of applying these constants to the data is in the form of a single program "correction.c", in which the bias-reducing correction, found in "[Correction for sensitivity and specificity](https://lernen.min.uni-hamburg.de/pluginfile.php/78026/mod_resource/content/1/est_prevalence.pdf)", is applied, since this is the only relevant occurrence of them in the R-script provided by Prof. Torda.
